import NextHead from "next/head";
import React, { Component } from "react";

export class Head extends Component {
  render() {
    return (
      <NextHead>
        {/* ----  PROJECT CONFIG ---- */}

        <title>RZ nextjs-temaplate </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Keywords" />
        <link rel="icon" href="/icons.icon.ico" />

        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />

        {/* ----  PWA CONFIG ---- */}

        <link rel="manifest" href="/manifest.json" />
        <link
          href="/icons.icon.png"
          rel="icon"
          type="image/png"
          sizes="16x16"
        />
        <link
          href="/icons.icon.png"
          rel="icon"
          type="image/png"
          sizes="32x32"
        />
        <link rel="apple-touch-icon" href="/icons.icon.png"></link>
        <meta name="theme-color" content="#317EFB" />
      </NextHead>
    );
  }
}

export default Head;
